if(NOT DEFINED src_folder)
	set(src_folder "src")
endif()

if(NOT DEFINED src_list)
	file(GLOB_RECURSE src_list "${src_folder}/*.c*")
	if("${BUILD_OS}" STREQUAL "Darwin" OR "${BUILD_OS}" STREQUAL "iPhone")
		file(GLOB_RECURSE src_platform_list "${src_folder}/*.m*")
	endif()
endif()
